### ISSUE TITLE
Fix Try

### ISSUE THREAD

**Issue by Ihsan48** [Henry12960/WorldChat#2]
Fix in WorldChat.php line 16:
From public function onEnable() {
To public function onEnable() : void {

Fix to EvenrtListener.php line 7
From use pocketmine\Player;
To use pocketmine\player\Player;

**Comment by Henry12960** [comment]
thanks for reporting a bug, i will fix it soon

**Comment by Henry12960** [comment]
Fix... i really don't know why i put this lol

**Comment by Henry12960** [comment]
Fixed! I'm still finishing and fixing other bugs, any reporter errors!
