### ISSUE TITLE
Try

### ISSUE THREAD

**Issue by Ihsan48** [Henry12960/WorldChat#4]
In EventListener.php Line 24
From if($this->plugin->isChatDisabled($player->getLevel()->getName())) {
To if($this->plugin->isChatDisabled($player->getWorld()->getDisplayName())) {
And In EventListener.php Line 33
From if($recipient->getLevel() != $player->getLevel()){
To if($recipient->getWorld() != $player->getWorld()){

**Comment by Henry12960** [comment]
literally you are helping me a lot, I only know the php 8 code, not pocketmine lol
