### ISSUE TITLE
Future Update

### ISSUE THREAD

**Issue by BoyKage** [Henry12960/WorldChat#8]
guy manages to make a plugin talk on the global? local and global type?

**Comment by Henry12960** [comment]
hummmm good ideia

**Comment by BoyKage** [comment]
🙂

**Comment by Ihsan48** [comment]
Ummmm, Maybe I'll think about it in the future

**Comment by Ihsan48** [comment]
Sorry, I want to ask further. Did you mean like /global is like /say in Pocketmine? And what is /local used for and what mechanic do you want?

**Comment by BoyKage** [comment]
it's like when another player is in another world you give /g (and the conversation) to chat with people who are not in the same world. and /local. it would be for those who are close to you.

**Comment by BoyKage** [comment]
But like not needing to give /location to talk to whoever is nearby... Eh, just write in chat, and it will send the message to whoever is close by.

**Comment by Ihsan48** [comment]
I will implement Global Chat as soon as possible, and for Local itself, I don't think it's useful. because we only need to do a normal chat without the need to use Command

**Comment by BoyKage** [comment]
hum ok... I want to test it when it's ready, maybe without the place I think it's good too... when do you intend to do it and finish?

**Comment by Henry12960** [comment]
I'm currently focused on my new mega plugin: https://github.com/Henry12960/CustomPVP but I'll see if I can do it here asap

**Comment by Henry12960** [comment]
> hum ok... quero testar quando estiver pronto, talvez sem o lugar acho bom também... quando pretende fazer e terminar?

I'm currently focused on my new mega plugin: https://github.com/Henry12960/CustomPVP but I'll see if I can do it here asap

**Comment by BoyKage** [comment]
Ok
